### ISSUE TITLE
Error when trying to find team.

### ISSUE THREAD

**Issue by josemariaaguilera** [tohkev/tk-splinterlands-bot#1]
When the bot is calling the API to find a team, it tries to call the endpoint 
`http://localhost:5000/getteams?ruleset=&mana=no mana&player=jotacryptotest&summoners=[]&gladius=false`
but it throws this error
`fetch  FetchError: request to http://localhost:5000/getteams?ruleset=&mana=no%20mana&player=jotacryptotest&summoners=[]&gladius=false failed, reason: connect ECONNREFUSED 127.0.0.1:5000
`

**Comment by josemariaaguilera** [comment]
I can't see any http server listening to any port and couldn't find anything about it in the code neither

**Comment by tohkev** [comment]
Hello, my bot is currently running on a private API I created. The localhost:5000 is a placeholder for that private API. As for the route you are getting, can you take a screenshot of the console logs you see?

**Comment by josemariaaguilera** [comment]
this is what I'm getting. I have no quest becuase this is a test account and it hasn't the spellbook purchased, but the username is properly setted in the .env file
[24:08:21] Your current Energy Capture Rate is 100%
[24:08:21] Error for quest details. Splinterlands API didnt work or you used incorrect username, remove @ and dont use email
[24:08:22] jotacryptotest  deck size: 108
[24:08:22] claim daily quest setting: false focus details:  undefined
[24:08:37] waiting for selector `#find_opponent_dialog` failed: timeout 10000ms exceeded
btn--create-team not detected
[24:08:42] Launch battle iter-[1]
[24:08:52] waiting for selector `#find_opponent_dialog` failed: timeout 10000ms exceeded
[24:09:04] API call:  http://localhost:5000/getteams?ruleset=&mana=no mana&player=jotacryptotest&summoners=[]&gladius=false
[24:09:04] fetch  FetchError: request to http://localhost:5000/getteams?ruleset=&mana=no%20mana&player=jotacryptotest&summoners=[]&gladius=false failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (/home/jota/Desktop/tk-splinterlands-bot/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
[24:09:04] No team found. 2nd attempt to find team..
[24:09:04] API call:  http://localhost:5000/getteams?ruleset=&mana=no mana&player=jotacryptotest&summoners=[]&gladius=false
[24:09:04] fetch  FetchError: request to http://localhost:5000/getteams?ruleset=&mana=no%20mana&player=jotacryptotest&summoners=[]&gladius=false failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (/home/jota/Desktop/tk-splinterlands-bot/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
[24:09:04] No teams found, skipping game..
[24:09:04] Closing battle 6/1/2022, 12:09:04 AM

As you say you have an private API, I think the issue could be that I can't access that private API, as I see in the code the localhost:5000 is just a placeholder but it would use the API env variable if exists here
https://github.com/tohkev/tk-splinterlands-bot/blob/master/possibleTeams.js#L114

**Comment by tohkev** [comment]
Hello Jose,

It looks like a couple of the usual logs were missing, can you re-pull the latest version and send over the logs? 

I also add a couple more logs when getting match information. The URL should at least contain the match ruleset, mana, and summoner lists.

**Comment by josemariaaguilera** [comment]
Hi, here i am with the latest changes in the repo

[18:03:54] logged in!
[18:04:23] Your current Energy Capture Rate is 100%
[18:04:24] Error for quest details. Splinterlands API didnt work or you used incorrect username, remove @ and dont use email
[18:04:24] jotacryptotest  deck size: 108
[18:04:24] claim daily quest setting: false focus details:  undefined
[18:04:30] Launching battle..
[18:04:40] waiting for selector `#find_opponent_dialog` failed: timeout 10000ms exceeded
btn--create-team not detected
[18:04:45] Launch battle iter-[1]
[18:04:55] waiting for selector `#find_opponent_dialog` failed: timeout 10000ms exceeded
[18:05:05] Getting mana..
[18:05:05] Getting ruleset..
[18:05:05] Getting active splinters..
[18:05:07] API call:  http://localhost:5000/getteams?ruleset=&mana=no mana&player=jotacryptotest&summoners=[]&gladius=false
[18:05:07] fetch  FetchError: request to http://localhost:5000/getteams?ruleset=&mana=no%20mana&player=jotacryptotest&summoners=[]&gladius=false failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (/home/jota/Desktop/tk-splinterlands-bot/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
[18:05:07] No team found. 2nd attempt to find team..
[18:05:07] API call:  http://localhost:5000/getteams?ruleset=&mana=no mana&player=jotacryptotest&summoners=[]&gladius=false
[18:05:07] fetch  FetchError: request to http://localhost:5000/getteams?ruleset=&mana=no%20mana&player=jotacryptotest&summoners=[]&gladius=false failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (/home/jota/Desktop/tk-splinterlands-bot/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
[18:05:07] No teams found, skipping game..
[18:05:07] Closing battle 6/1/2022, 6:05:07 PM

**Comment by josemariaaguilera** [comment]
I'm still thinking the problem is the API host. I have no private API so... it will not work if I dont build it?

**Comment by tohkev** [comment]
Hey Jose,

A missing API host would actually lead to a different error I believe. Can you confirm a couple of things:
- Are you running the bot using 'npm start'?
- Are you using username and posting key combination in the .env file?
- Is "logged in" the first log that appears for you?

Looks like the games aren't starting at all based on your end. This bot should be using your information to start a game and gather the game data. If a backend API is missing, you should have a forfeited game in your history due to no teams submitted.

**Comment by josemariaaguilera** [comment]
I've removed the node_modules, installed all from scratch and run npm install

I have the username and posting key properly setted in the .env file 

and before the "logged in" message I'm getting this

```
node main.js

[23:22:48] isMultiAccountMode: false
[23:22:48] Running mode: single
[23:22:48] START  jotacryptotest 6/1/2022, 11:22:48 PM
[23:22:48] Recover Status:  0
[23:22:48] 6/1/2022, 11:22:48 PM opening browser...
[23:23:03] browser page error:  Error: SyntaxError: Unexpected token ';'
    at p (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:310485)
    at Ja (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:357815)
    at r.fn.init.append (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:359086)
    at r.fn.init.<anonymous> (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:360190)
    at T (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:342386)
    at r.fn.init.html (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:359868)
    at Object.ShowHomeView (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:40269)
    at ShowAbout (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:68585)
    at Object.OnDialogHidden (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:42025)
    at HTMLDivElement.<anonymous> (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:41660)
    at HTMLDivElement.dispatch (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:352304)
    at HTMLDivElement.q.handle (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:350331)
    at Object.trigger (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:379666)
    at HTMLDivElement.<anonymous> (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:380176)
    at Function.each (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:312677)
    at r.fn.init.each (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:310965)
[23:23:09] browser page error:  Error: SyntaxError: Unexpected token ';'
    at p (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:310485)
    at Ja (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:357815)
    at r.fn.init.append (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:359086)
    at r.fn.init.<anonymous> (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:360190)
    at T (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:342386)
    at r.fn.init.html (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:359868)
    at Object.ShowHomeView (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:40269)
    at Object.ShowAbout (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:68585)
    at Object.ShowUrlPage (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:47301)
    at https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:48578
    at https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:49687
    at https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:59570
    at Object.success (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:35282)
    at i (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:337974)
    at Object.fireWith [as resolveWith] (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:338740)
    at A (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:388072)
[23:23:15] browser page error:  Error: SyntaxError: Unexpected token ';'
    at p (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:310485)
    at Ja (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:357815)
    at r.fn.init.append (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:359086)
    at r.fn.init.<anonymous> (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:360190)
    at T (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:342386)
    at r.fn.init.html (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:359868)
    at Object.ShowHomeView (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:40269)
    at Object.ShowAbout (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:68585)
    at Object.ShowUrlPage (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:47301)
    at https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:48578
    at https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:49687
    at https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:59570
    at Object.success (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/SM.min.js?v=1653405924757:1:35282)
    at i (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:337974)
    at Object.fireWith [as resolveWith] (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:338740)
    at A (https://dstm6no41hr55.cloudfront.net/220524/scripts/dist/libraries.min.js?v=1653405924757:1:388072)
[23:23:17] logged in!

```

**Comment by tohkev** [comment]
Looks like the error is stemming from puppeteer not being able to start up a browser properly. Based on that error before "logged in" is there any duplicating semicolons (";") you can find?

**Comment by josemariaaguilera** [comment]
it's like there is a library coming from cloudfront producing the error when trying to reach the splinterland page...

If I take a look into this cloudfront file it has double semicolons, but don't know how ot change it or avoid the loading

**Comment by josemariaaguilera** [comment]
I've filled the HEADLESS .env var to false so I can see the browser and the problem is that I can't reach the API.

I have no API running in my localhost and this code doesn't up any server so... I think the problem is the API.

is it suposed that I create the API?

I can see the game starting, and getting a loose game, but as the bot doesn't find any team, it keeps the battle confirmation modal open

**Comment by tohkev** [comment]
Hey Jose,

That is correct, the bot will start up a game for you and then send the game information to the backend (API) to retrieve a team to play. 

At this point, you will need to create your own API endpoint so that it will take the game information (ruleset, mana, active splinter, etc.) and calculate a team for you.
